---
Name: pp-indexnow--config
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - IndexNow\Extensions\SiteConfigExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - IndexNow\Extensions\IndexNowExtension

IndexNow\Extensions\IndexNowExtension:
  excluded_classes:
    - SilverStripe\CMS\Model\RedirectorPage
    - SilverStripe\CMS\Model\VirtualPage

SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        IndexNowKeyMiddleware: '%$IndexNow\Middlewares\IndexNowKeyMiddleware'
