---
Name: pp-indexnow--config
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - IndexNow\Extensions\SiteConfigExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - IndexNow\Extensions\PageExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        IndexNowKeyMiddleware: '%$IndexNow\Middlewares\IndexNowKeyMiddleware'
